name: caihong_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.14

environment:
  sdk: '>=2.7.0 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # Bilibili开源的视频播放组件
  fijkplayer: ^0.10.0
  fijkplayer_skin: ^2.2.8
  ###volume_controller: ^2.0.2
  ###screen_brightness: ^0.0.2

  # 加载动画库
  flutter_spinkit: ^4.1.2

  #视频播放
  ###flutter_staggered_grid_view: ^0.4.1
  ###transparent_image: ^2.0.0


  # 基础的点击
  tapped: any
  # map取值
  safemap: any

  # 下拉刷新上拉加载
  pull_to_refresh: ^2.0.0

  #toast
  fluttertoast: ^8.0.2

  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  ###common_utils: ^2.1.0

  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars: ^2.0.0

  # Flutter 国际化/多语言库 https://github.com/Sky24n/fluintl
  ###fluintl: ^0.1.2

  # https://github.com/flutterchina/dio
  dio: ^5.0.3

  # rxdart https://github.com/ReactiveX/rxdart
  ###rxdart: ^0.27.7

  # https://github.com/renefloor/flutter_cached_network_image
  #  cached_network_image: ^1.1.3
  cached_network_image: ^3.2.0

  # https://github.com/flutter/plugins/tree/master/packages/url_launcher
  ###url_launcher: ^5.0.2

  # 格式化String https://github.com/Naddiseo/dart-sprintf
  sprintf: ^4.0.2

  # https://github.com/flutterchina/flukit.
  ###flukit: ^1.0.0

  #状态管理
  ###provider: ^3.0.0+1


  # 路由框架 https://github.com/theyakka/fluro
  fluro: ^1.5.1

  # 处理键盘事件 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^3.1.1

  #https://github.com/marcojakob/dart-event-bus
  event_bus: ^1.1.0

  #获取应用包的信息 https://github.com/flutter/plugins/tree/master/packages/package_info
  package_info: ^0.4.0+2

  flutter_xupdate: ^2.0.2

  # https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  webview_flutter: ^ 0.3.18+1

  #https://github.com/leisim/logger.git  日志工具
  logger: ^0.6.0

  #打开相册
  ###image_picker: ^0.6.1+4

  #持久化存储
  shared_preferences: ^2.0.13

  #七牛云
  ###qiniu_flutter_sdk: ^0.5.0

  #FFmpeg
#  flutter_ffmpeg: ^0.4.2

  #数据库
  ###sqflite: ^2.2.8+1

  #Dart路径操作库
  ###path: ^1.8.0

  #轮播 图插件
  flutter_swiper_null_safety: ^1.0.2

  device_info: ^0.4.0+4

  http: 0.13.2

  ### 生成二维码
  qr_flutter: ^3.2.0

  ### 图片保存
  permission_handler: ^10.0.2

  ### 分享库
  share: ^0.6.5+4

  image_gallery_saver: ^1.6.6

  ### 文档操作
  path_provider: ^2.0.0

  ### 桌面操作
  screen_capturer: ^0.1.0

  ### 调用浏览器 打开URL
  url_launcher: ^5.2.7

  ###volume_controller: ^2.0.2
  ###screen_brightness: ^0.0.2

  flutter_staggered_grid_view: ^0.4.1
  transparent_image: ^2.0.0
  volume_controller: ^2.0.2
  screen_brightness: ^0.0.2
  ### 本地通知
  flutter_local_notifications: ^15.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - lib/assets/images/logo.png
    - lib/assets/images/recharge.png
    - lib/assets/images/use_gold_watch.png
    - lib/assets/images/search.png
    - lib/assets/images/sign.png
    - lib/assets/images/recommend.png
    - lib/assets/images/grocery_card.png
    - lib/assets/images/group.png
    - lib/assets/images/vip_user.png
    - lib/assets/images/title_icon.png
    - lib/assets/images/next.png
    - lib/assets/images/show_level_icon.png
    - lib/assets/images/vip_show_level.png
    - lib/assets/images/free_show_level.png
    - lib/assets/images/gold_icon.png
    - lib/assets/images/fresh.png
    - lib/assets/images/player_pause.png
    - lib/assets/images/home_2_active.png
    - lib/assets/images/home_2_inactive.png
    - lib/assets/images/short_video_2_inactive.png
    - lib/assets/images/short_video_2_active.png
    - lib/assets/images/topic_2_inactive.png
    - lib/assets/images/topic_2_active.png
    - lib/assets/images/find_2_inactive.png
    - lib/assets/images/find_2_active.png
    - lib/assets/images/mine_2_inactive.png
    - lib/assets/images/mine_2_active.png
    - lib/assets/images/favorite_white.png
    - lib/assets/images/favorite_red.png
    - lib/assets/images/star_white.png
    - lib/assets/images/star_yellow.png
    - lib/assets/images/cache_down_load.png
    - lib/assets/images/switch.png
    - lib/assets/images/comment.png
    - lib/assets/images/share.png
    - lib/assets/images/upload_video.png
    - lib/assets/images/movie.png
    - lib/assets/images/charge_gold.png
    - lib/assets/images/cancel.png
    - lib/assets/images/wechat_pay.png
    - lib/assets/images/alipay.png
    - lib/assets/images/pay_icon.png
    - lib/assets/images/checked.png
    - lib/assets/images/search_no_result.png
    - lib/assets/images/advoce.png
    - lib/assets/images/gift.png
    - lib/assets/images/gold_medal.png
    - lib/assets/images/share_earn_money.png
    - lib/assets/images/camera.png
    - lib/assets/images/collect.png
    - lib/assets/images/user.png
    - lib/assets/images/video_icon.png
    - lib/assets/images/user_vip_background.png
    - lib/assets/images/shopping_car.png
    - lib/assets/images/down_load.png
    - lib/assets/images/invite_num.png
    - lib/assets/images/exchange.png
    - lib/assets/images/help.png
    - lib/assets/images/telegram.png
    - lib/assets/images/setting.png
    - lib/assets/images/vip_dialog_img.png
    - lib/assets/images/red_circle.png
    - lib/assets/images/vip/season_vip.png
    - lib/assets/images/vip/superior_vip.png
    - lib/assets/images/vip/three_day_vip.png
    - lib/assets/images/vip/week_vip.png
    - lib/assets/images/vip/year_vip.png
    - lib/assets/images/vip/month_vip.png
    - lib/assets/images/vip/buy_vip_background.png
    - lib/assets/images/vip/vip_hat.png
    - lib/assets/images/vip/kefu.png
    - lib/assets/images/vip/neirong_pipei.png
    - lib/assets/images/vip/vip_video.png
    - lib/assets/images/vip/comment_publish.png
    - lib/assets/images/vip/lunpan.png
    - lib/assets/images/vip/shishi_shouqi.png
    - lib/assets/images/vip/meiri_zhekou.png
    - lib/assets/images/vip/shuangbei_jiangli.png
    - lib/assets/images/vip/xianlu_qiehuan.png
    - lib/assets/images/vip/gexin_shezhi.png
    - lib/assets/images/vip/yijian_qifei.png
    - lib/assets/images/vip/quanpin_datu.png
    - lib/assets/images/vip/zhekou.png
    - lib/assets/images/vip/skip_ad.png
    - lib/assets/images/vip/open_vip_bcg.png
    - lib/assets/images/vip/open_vip_kefu.png
    - lib/assets/images/vip/open_vip_video.png
    - lib/assets/images/vip/open_vip_switch.png
    - lib/assets/images/myvip/vip_fuli.png
    - lib/assets/images/myvip/vip_log.png
    - lib/assets/images/myvip/my_vip_background.png
    - lib/assets/images/sign/ad_live.png
    - lib/assets/images/sign/gift_package.png
    - lib/assets/images/sign/golden.png
    - lib/assets/images/sign/his_icon.png
    - lib/assets/images/sign/vip.png
    - lib/assets/images/sign/watch_movie.png
    - lib/assets/images/share/00389.png
    - lib/assets/images/share/00396.png
    - lib/assets/images/share/00398.png
    - lib/assets/images/share/00399.png
    - lib/assets/images/share/douban.png
    - lib/assets/images/share/erweima.png
    - lib/assets/images/share/header_background.png
    - lib/assets/images/share/lualu.png
    - lib/assets/images/share/menghuanxiyou.png
    - lib/assets/images/share/qq.png
    - lib/assets/images/share/renren.png
    - lib/assets/images/share/sina.png
    - lib/assets/images/share/soul.png
    - lib/assets/images/share/tantan.png
    - lib/assets/images/share/tiktok.png
    - lib/assets/images/share/wangzherongyao.png
    - lib/assets/images/share/wechat.png
    - lib/assets/images/share/zhihu.png
    - lib/assets/images/video_pause.png
    - lib/assets/images/head_icon.gif

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
